### ISSUE TITLE
undefined reference to `dlsym'

### ISSUE THREAD

**Issue by mottosso** [feather3d/feather#9]
Getting an error during build for the [latest commit](https://github.com/feather3d/feather/tree/b98bd65b2dc6321e07f8b5f0b052143f8eeedf41).

Not sure what it could be, StackOverflow suggests a compiler flag of sorts.

- http://stackoverflow.com/questions/20369672/undefined-reference-to-dlsym

```
$ make
[ 86%] Built target feather_qml
[ 93%] Built target feather
Linking CXX executable coretest
../lib/core/libfeather_core.so.0.01: undefined reference to `dlsym'
../lib/core/libfeather_core.so.0.01: undefined reference to `dlerror'
../lib/core/libfeather_core.so.0.01: undefined reference to `dlopen'
../lib/core/libfeather_core.so.0.01: undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
make[2]: *** [src/test/coretest] Error 1
make[1]: *** [src/test/CMakeFiles/coretest.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by richardlayman** [comment]
set(CMAKE_CXX_LINK_FLAGS "-ldl") in the root CMakeLists.txt should have caught this. GCC might be having a problem locating libdl.so, is it in the /usr/lib ?

**Comment by mottosso** [comment]
Doesn't look like it's there.

It built successfully before, if that matters.

Is it a dependency? Sorry, haven't come across this particular library before.

**Comment by richardlayman** [comment]
I Arch it's part of the glibc package

**Comment by mottosso** [comment]
Fixed with https://github.com/feather3d/feather/pull/10
